
server:
  port: 8080
  servlet:
    contextPath: /${spring.application.name}/v1/
spring:
  application:
    name: mssivimss-procesos
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  cache:
    redis:
      time-to-live: 30000
      
  datasource:
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SIVIBDDS?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Mexico_City #jdbc:mysql://10.102.44.18:3306/SIVIBDDS
    username: root #pmsoluciones #root
    password: root #Tr1357.* #Maria2023
    timeBetweenEvictionRunsMillis: 1000
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
       max-lifetime: 1800000
       idle-timeout: 600000
       connection-timeout: 30000
       auto-commit: false
       maximum-pool-size: 7
       minimum-idle: 10
      
      
  main:
    allow-circular-references: true
    
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
            
logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: error

 

jwt:
  secretkey-flujo:  funcionamuybien
  expiration-milliseconds: 360

management:
      endpoints:
          web:
            exposure:
                include:
                    health,info,metrics

numero-por-grupo: 5

ruta-log: 'C:/logs/'

